### ISSUE TITLE
Segmentation fault on sparse file

### ISSUE THREAD

**Issue by jdecourval** [bertbaron/btrdedup#1]
Hi,

Today I tried btrdedup on my server, but it systematically crash with a segmentation fault in the Pass 3 (deduplucating files), always after seeing a sparse file.

btrdedup progress a little further each time I restart it.

command line used:
```
sudo nice -n 10 ./btrdedup -defrag /mnt/btrfs 2>dedup.log
```

kernel: 5.3.7-arch1-1-ARCH
OS: ArchLinux
btrfs-progs: 5.4

```
./btrdedup -version                                                                                                                                                                    
btrdedup version '0.2.0' built at '2019-11-27T14:06:47+0000'
```

```
2019/12/26 13:28:00 File /path/to/file has 251 fragments while we want max 3, starting defragmentation
2019/12/26 13:28:00 Skipping sparse file /path/to/file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4fcf8b]

goroutine 1 [running]:
main.reorderAndDefragIfNeeded(0x575da0, 0xc0000980f0, 0xc00006c420, 0x576400, 0xc00000e140, 0xc0004da000, 0x1, 0x200, 0x400, 0xc000028f00, ...)
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/main.go:247 +0x78b
main.submitForDedup(0x575da0, 0xc0000980f0, 0xc00006c420, 0x576400, 0xc00000e140, 0xc0004da000, 0x1, 0x200, 0x400, 0x200)
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/main.go:270 +0xd4
main.pass3.func1(0xc0004da000, 0x1, 0x200)
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/main.go:357 +0x99
github.com/bertbaron/btrdedup/storage.(*MemoryBased).PartitionOnHash(0xc00000e140, 0xc0092c6900)
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/storage/memorybased.go:97 +0x172
main.pass3(0x575da0, 0xc0000980f0, 0xc00006c420, 0x576400, 0xc00000e140, 0x400, 0x0)
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/main.go:356 +0x10c
main.main()
	/home/travis/gopath/src/github.com/bertbaron/btrdedup/main.go:445 +0x6cc
tail: dedup.log: file truncated

```

**Comment by bertbaron** [comment]
Thanks for reporting the issue.

Looking into the code the stacktrace seems to indicate that the defragmentation resulted in a sparse file. The code (I) didn't expect that to happen. On the next run, the sparse copy is skipped (since those are not supported) so the code will fail on the next duplicate resulting in a sparse file.

It would be easy for me to fix the nil pointer dereference at the given position but it may still result in problems further down the line, so I need a bit more time.

Note that when this is fixed and you run it again, you will end up with defragmented sparse copies of your file, they will not be deduplicated unfortunately. Whether this will result  in more or less space used on your file system depends on how sparse the files are.

**Comment by bertbaron** [comment]
@jdecourval I made a fix and released it in https://github.com/bertbaron/btrdedup/releases/tag/0.2.1

Could you try to see if this fixes the issue?

It will defrag but not deduplicate the file if it becomse sparse. The best solution would of course be to support sparse files but that will require some effort.

**Comment by jdecourval** [comment]
Thanks @bertbaron for that quick fix.

It took a few hours but I just successfully completed a new run of `btrdedup` with your new build. However, it looks like I didn't have any problematic file remaining on my file system:

```
% grep 'File can not be deduplicated after' dedup.log                                                                                                                                     
1 % grep 'file may be sparse' dedup.log                                                                                                                                                     
2019/12/27 11:06:15 Error while trying to get the fragments of file /mnt/btrfs/file1: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:20 Error while trying to get the fragments of file /mnt/btrfs/file2: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:20 Error while trying to get the fragments of file /mnt/btrfs/file3: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:20 Error while trying to get the fragments of file /mnt/btrfs/file4: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:31 Error while trying to get the fragments of file /mnt/btrfs/file5: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:32 Error while trying to get the fragments of file /mnt/btrfs/file6: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:32 Error while trying to get the fragments of file /mnt/btrfs/file7: Failed to read fragments for file: No (more) extends found, file may be sparse
2019/12/27 11:06:34 Error while trying to get the fragments of file /mnt/btrfs/file8: Failed to read fragments for file: No (more) extends found, file may be sparse
```

Do you know any way to create a fragmented file that become sparse after defragmentation? I tried creating such a file with a few combinations of `dd`, `fallocate` and `truncate` without success.

**Comment by bertbaron** [comment]
Thanks for testing. I'm pretty sure that at least the crash will not happen again now but I also didn't manage to properly reproduce (I had to tweak a bit). I don't totally understand what causes the issue. What happens is that after defragmentation the actual size on the filesystem differs from the perceived file size. Maybe the file gets compressed instead of becoming sparse?

Anyway, the program should be more robust now so I think I can close this issue. I'll have to look into proper handling of sparse and compressed files in the future.

**Comment by jdecourval** [comment]
I indeed have zstd compression activated. 

Thank you for your support, I will open a new issue if this problem ever happens again.
